declare module '@env' {
	export const INFURA_API_KEY: string;
	export const INFURA_PROJECT_SECRET: string;
	export const WALLET_CONNECT_PROJECT_ID: string;
	export const WYRE_MERCHANT_ID_TEST: string;
	export const WYRE_MERCHANT_ID: string;
	export const WYRE_ACCOUNT_ID_TEST: string;
	export const WYRE_ACCOUNT_ID: string;
	export const WYRE_TOKEN: string;
	export const WYRE_TOKEN_TEST: string;
	export const COVALENT_API_KEY: string;
	export const MINKE_MASTER_KEY: string;
	export const AMPLITUDE_PROJECT_API: string;
	export const SENTRY_DSN: string;
	export const ALCHEMY_API_URL_POLYGON_MAINNET: string;
	export const BICONOMY_API_KEY_POLYGON_MAINNET: string;
	export const ALCHEMY_API_KEY_ETHEREUM: string;
	export const ALCHEMY_API_KEY_MATIC: string;
	export const ALCHEMY_API_KEY_ROPSTEN: string;
	export const ALCHEMY_API_KEY_KOVAN: string;
	export const BANXA_ENDPOINT_URL: string;
	export const BANXA_KEY: string;
	export const BANXA_SECRET: string;
	export const APPS_FLYER_DEV_KEY: string;
	export const INTERCOM_KEY: string;
}
